'use client';
import { FormEvent, useState } from 'react';
import { useAuth } from '@/lib/auth-context';

export default function ProfilePage() {
  const { user, updateProfile, logout } = useAuth();
  const [name, setName] = useState(user?.full_name || '');
  const [company, setCompany] = useState(user?.company_name || '');
  const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false);
  async function save(e: FormEvent) { e.preventDefault(); setSaving(true); setMessage(''); const result = await updateProfile({ full_name: name, company_name: company, new_password: password || undefined }); setSaving(false); setMessage(result.success ? 'Your profile is up to date.' : (result.error || 'Could not save changes.')); if (result.success) setPassword(''); }
  if (!user) return null;
  return <main className="mx-auto w-full max-w-4xl space-y-6 p-5 sm:p-8"><div><p className="text-sm font-semibold text-indigo-600">Account</p><h1 className="mt-1 text-3xl font-extrabold tracking-tight text-slate-900">Your profile</h1><p className="mt-2 text-sm text-slate-500">Keep your details current so your workspace stays personal and secure.</p></div><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><section className="rounded-3xl bg-gradient-to-br from-indigo-600 to-indigo-800 p-7 text-white shadow-xl shadow-indigo-200"><div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-white/20 text-2xl font-extrabold">{user.full_name.split(' ').map(x => x[0]).join('').slice(0,2).toUpperCase()}</div><h2 className="mt-6 text-2xl font-bold">{user.full_name}</h2><p className="mt-1 text-sm text-indigo-100">{user.email}</p><div className="mt-8 border-t border-white/20 pt-5"><p className="text-xs uppercase tracking-widest text-indigo-200">Workspace</p><p className="mt-1 font-semibold">{user.company_name}</p></div><button onClick={logout} className="mt-8 rounded-xl border border-white/30 px-4 py-2.5 text-sm font-bold hover:bg-white/10">Log out</button></section><section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-lg font-bold text-slate-900">Personal details</h2><form onSubmit={save} className="mt-6 space-y-5"><label className="block text-sm font-semibold text-slate-700">Full name<input value={name} onChange={e => setName(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500" /></label><label className="block text-sm font-semibold text-slate-700">Business name<input value={company} onChange={e => setCompany(e.target.value)} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500" /></label><label className="block text-sm font-semibold text-slate-700">New password <span className="font-normal text-slate-400">(optional)</span><input minLength={8} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Leave blank to keep your current password" className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3 font-normal outline-none focus:border-indigo-500" /></label>{message && <p className="rounded-xl bg-indigo-50 px-4 py-3 text-sm text-indigo-700">{message}</p>}<button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white hover:bg-indigo-700 disabled:opacity-50">{saving ? 'Saving…' : 'Save changes'}</button></form></section></div></main>;
}
