'use client';
import { FormEvent, ReactNode, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CheckCircle2, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck, Sparkles } from 'lucide-react';
import { useAuth } from '../../lib/auth-context';

export default function LoginPage() {
  const router = useRouter(); const { login, register } = useAuth();
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [fullName, setFullName] = useState(''); const [businessName, setBusinessName] = useState('');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const result = mode === 'login' ? await login(email, password) : await register({ email, password, full_name: fullName, company_name: businessName }); setBusy(false); if (!result.success) { setError(result.error || 'Authentication failed.'); return; } router.replace('/'); }

  return <main className="min-h-screen w-full bg-cover bg-center bg-fixed flex items-stretch" style={{ backgroundImage: "linear-gradient(115deg, rgba(8,18,42,.28), rgba(8,18,42,.12)), url('/auth-background.png')" }}><div className="grid min-h-screen w-full lg:grid-cols-[.9fr_1.1fr]">
    <section className="relative hidden min-h-screen overflow-hidden p-8 xl:p-14 lg:flex lg:flex-col lg:justify-between"><div className="relative z-10"><Brand /><h2 className="mt-20 max-w-md text-5xl font-extrabold leading-[1.05] tracking-[-.04em] text-white drop-shadow-lg">Recover what matters.<br /><span className="text-indigo-200">Grow with confidence.</span></h2><p className="mt-6 max-w-md text-base leading-7 text-white/90 drop-shadow">See every failed payment, understand what happened, and take the next best step without the busywork.</p></div><div className="relative z-10 grid max-w-md gap-3">{['Spot payment problems early', 'Follow a safer recovery plan', 'Keep a clear record of every decision'].map(x => <div key={x} className="flex items-center gap-3 rounded-2xl border border-white/25 bg-slate-950/25 px-4 py-3 text-sm font-semibold text-white backdrop-blur-sm"><CheckCircle2 className="h-5 w-5 text-indigo-200" />{x}</div>)}</div></section>
    <section className="auth-panel flex min-h-screen items-center p-5 sm:p-10 lg:p-14 xl:p-20"><div className="mx-auto w-full max-w-xl rounded-[28px] border border-white/35 bg-slate-950/45 p-6 shadow-2xl shadow-slate-950/20 backdrop-blur-xl sm:p-10"><div className="mb-8 flex gap-8 border-b border-white/25"><Tab active={mode === 'login'} onClick={() => setMode('login')}>Sign in</Tab><Tab active={mode === 'register'} onClick={() => setMode('register')}>Create account</Tab></div><h1 className="text-3xl font-extrabold tracking-tight text-white">{mode === 'login' ? 'Welcome back 👋' : 'Start recovering revenue'}</h1><p className="mt-2 text-sm text-white/75">{mode === 'login' ? 'Sign in to your merchant workspace.' : 'Set up your workspace in a couple of minutes.'}</p>
      <form onSubmit={submit} className="mt-8 space-y-5">{mode === 'register' && <><Field label="Your name" icon={<Sparkles className="h-4 w-4" />}><input required value={fullName} onChange={e => setFullName(e.target.value)} placeholder="e.g. Priya Shah" className="auth-input" /></Field><Field label="Business name" icon={<ShieldCheck className="h-4 w-4" />}><input required value={businessName} onChange={e => setBusinessName(e.target.value)} placeholder="e.g. Acme Store" className="auth-input" /></Field></>}<Field label="Email address" icon={<Mail className="h-4 w-4" />}><input required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@company.com" className="auth-input" /></Field><Field label="Password" icon={<LockKeyhole className="h-4 w-4" />}><div className="relative"><input required minLength={8} type={showPassword ? 'text' : 'password'} value={password} onChange={e => setPassword(e.target.value)} placeholder="At least 8 characters" className="auth-input pr-11" /><button type="button" onClick={() => setShowPassword(v => !v)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400" aria-label="Toggle password visibility">{showPassword ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></div></Field>{mode === 'login' && <div className="flex items-center justify-between text-xs"><label className="flex items-center gap-2 text-slate-500"><input type="checkbox" className="h-4 w-4 accent-indigo-600" defaultChecked />Remember me</label><a href="/forgot-password" className="font-semibold text-indigo-600">Forgot password?</a></div>}{error && <p role="alert" className="rounded-xl border border-red-300/40 bg-red-950/70 px-4 py-3 text-sm font-semibold text-red-50 shadow-lg shadow-red-950/20">{error}</p>}<button disabled={busy} className="w-full rounded-xl bg-indigo-600 px-4 py-3.5 text-sm font-bold text-white shadow-lg shadow-indigo-200 hover:bg-indigo-700 disabled:opacity-50">{busy ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form>
      <div className="my-7 flex items-center gap-3 text-xs text-slate-400"><span className="h-px flex-1 bg-slate-200" />or continue with<span className="h-px flex-1 bg-slate-200" /></div><button type="button" onClick={() => setError('Google sign-in will be available once Google OAuth is configured for this workspace.')} className="flex w-full items-center justify-center gap-3 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-700 hover:border-indigo-200 hover:bg-indigo-50"><GoogleIcon />Continue with Google</button><p className="mt-8 text-center text-xs leading-5 text-slate-400">By continuing, you agree to use RecoverAI responsibly and keep your account secure.</p></div></section>
  </div></main>;
}
function Brand() { return <div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><ShieldCheck className="h-6 w-6" /></div><div><p className="text-xl font-extrabold tracking-tight text-white drop-shadow">Recover<span className="text-indigo-200">AI</span></p><p className="text-xs text-white/80">Payment recovery, made clear.</p></div></div>; }
function Tab({ active, onClick, children }: { active: boolean; onClick: () => void; children: ReactNode }) { return <button type="button" onClick={onClick} className={`-mb-px pb-4 text-base font-bold ${active ? 'border-b-2 border-indigo-600 text-indigo-600' : 'text-slate-400'}`}>{children}</button>; }
function Field({ label, icon, children }: { label: string; icon: ReactNode; children: ReactNode }) { return <label className="block"><span className="mb-2 flex items-center gap-2 text-sm font-semibold text-slate-700">{icon}{label}</span>{children}</label>; }
function GoogleIcon() { return <svg width="18" height="18" viewBox="0 0 24 24" aria-hidden="true"><path fill="#4285F4" d="M21.35 12.27c0-.72-.06-1.42-.18-2.09H12v3.96h5.24a4.48 4.48 0 0 1-1.94 2.94v2.45h3.14c1.84-1.7 2.91-4.2 2.91-7.26z"/><path fill="#34A853" d="M12 21.7c2.63 0 4.84-.87 6.45-2.37l-3.14-2.45c-.87.58-1.98.92-3.31.92-2.54 0-4.7-1.72-5.47-4.03H3.29v2.53A9.74 9.74 0 0 0 12 21.7z"/><path fill="#FBBC05" d="M6.53 13.77a5.85 5.85 0 0 1 0-3.54V7.7H3.29v2.53l3.24 2.53z"/><path fill="#EA4335" d="M12 6.2c1.43 0 2.71.49 3.72 1.45l2.79-2.79C16.84 3.27 14.63 2.3 12 2.3a9.74 9.74 0 0 0-8.71 5.4l3.24 2.53C7.3 7.92 9.46 6.2 12 6.2z"/></svg>; }
