"""
data/generate_data.py — Synthetic dataset generator for RecoverAI.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
DESIGN ASSUMPTIONS PER FAILURE REASON
(These drive both the data distribution AND the hidden ground-truth labels)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BANK_SERVER_DOWN (weight ~25%)
  - Cause: The bank's payment processor was temporarily unavailable.
  - Recovery: Very likely recoverable — it's not a customer problem.
    A retry or payment link a few hours later usually succeeds.
  - Ground truth: ~75–85% recoverable, with noise.
  - Amount distribution: full range (including some large amounts).

INSUFFICIENT_FUNDS (weight ~30%)
  - Cause: Customer's account balance was too low at time of payment.
  - Recovery: Often NOT immediately recoverable via retry — the money isn't
    there yet. However, a payment link sent 24–48 hrs later (hoping salary
    credited or funds moved) can work for loyal customers.
  - Ground truth: ~25–35% recoverable, strongly correlated with customer
    payment history (loyal customers are more likely to top up and return).
  - Amount distribution: skewed toward smaller amounts; large amounts are
    less likely to succeed if funds were insufficient.

NETWORK_TIMEOUT (weight ~20%)
  - Cause: Connection dropped mid-transaction (customer's network or
    gateway side). Payment may or may not have been deducted.
  - Recovery: High — usually just a transient glitch. Retry or resend link.
  - Ground truth: ~70–80% recoverable.
  - Amount distribution: full range.

CARD_EXPIRED (weight ~15%)
  - Cause: Customer's card reached its expiry date.
  - Recovery: NOT recoverable via retry — the card is dead. Recovery requires
    the customer to use a different payment method. A payment link (which
    lets them choose any method) can work, but only if the customer is
    motivated to pay.
  - Ground truth: ~20–30% recoverable (depends heavily on customer loyalty).

INVALID_OTP (weight ~10%)
  - Cause: Customer entered the wrong one-time password, or OTP expired
    before they entered it.
  - Recovery: Conditional — if the customer is willing to retry and enters
    the OTP correctly, it works. But repeat OTP failures suggest either
    phishing concern or a disengaged customer.
  - Ground truth: ~40–55% recoverable, drops sharply with previous_attempts.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
CIRCULAR-EVALUATION GUARD
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
The hidden `actual_recovery_outcome` in the `ground_truth` table is
generated by a SEPARATE, NOISIER function (_ground_truth_oracle) that
intentionally differs from the recovery_probability formula in diagnosis.py.

Specifically:
  - _ground_truth_oracle uses a different random seed path
  - It adds ±15% structured noise and 10% pure random exceptions
  - The base rates per failure type differ slightly from the heuristic's
    weights, so diagnosis.py cannot "cheat" by learning the exact formula

This means Phase 7 metrics (precision, recall, F1) will be genuinely
honest — the model cannot score 100% because the labels have intentional,
realistic noise.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

from __future__ import annotations

import os
import random
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

# Make project root importable when running this file directly
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

from dotenv import load_dotenv

load_dotenv()

from logging_config import get_logger, setup_logging
from db import drop_all_tables, get_connection, init_db
from models.schemas import (
    Customer,
    FailureReason,
    Payment,
    PaymentMethod,
    PaymentStatus,
)

logger = get_logger(__name__)   # module-level logger, available to all functions

# ── Constants ──────────────────────────────────────────────────────────────────

RANDOM_SEED = 42          # Fixed seed → reproducible run every time
N_CUSTOMERS = 150
N_PAYMENTS  = 500

# Weighted failure-reason distribution (must sum to 1.0)
FAILURE_WEIGHTS: dict[FailureReason, float] = {
    FailureReason.BANK_SERVER_DOWN:   0.25,
    FailureReason.INSUFFICIENT_FUNDS: 0.30,
    FailureReason.NETWORK_TIMEOUT:    0.20,
    FailureReason.CARD_EXPIRED:       0.15,
    FailureReason.INVALID_OTP:        0.10,
}

# Payment methods — UPI dominates in India
METHOD_WEIGHTS: dict[PaymentMethod, float] = {
    PaymentMethod.UPI:         0.45,
    PaymentMethod.DEBIT_CARD:  0.20,
    PaymentMethod.CREDIT_CARD: 0.18,
    PaymentMethod.NET_BANKING: 0.12,
    PaymentMethod.WALLET:      0.05,
}

# Amount ranges (in ₹)
# ~95% of payments: ₹200–₹10,000 (small/medium)
# ~5%  of payments: ₹10,001–₹75,000 (large — to test guardrail)
AMOUNT_SMALL_RANGE = (200.0, 10_000.0)
AMOUNT_LARGE_RANGE = (10_001.0, 75_000.0)
LARGE_PAYMENT_FRACTION = 0.05

# Payments span the last 30 days
NOW = datetime.now(timezone.utc)
EARLIEST_TIMESTAMP = NOW - timedelta(days=30)


# ── Helpers ────────────────────────────────────────────────────────────────────

def _weighted_choice(rng: random.Random, weights: dict[Any, float]) -> Any:
    """Pick one key from a dict using its float value as weight."""
    keys   = list(weights.keys())
    values = list(weights.values())
    return rng.choices(keys, weights=values, k=1)[0]


def _random_timestamp(rng: random.Random) -> datetime:
    delta_seconds = rng.uniform(0, (NOW - EARLIEST_TIMESTAMP).total_seconds())
    return EARLIEST_TIMESTAMP + timedelta(seconds=delta_seconds)


def _random_amount(rng: random.Random) -> float:
    """Return a payment amount; ~5% chance of being above ₹10,000."""
    if rng.random() < LARGE_PAYMENT_FRACTION:
        amount = rng.uniform(*AMOUNT_LARGE_RANGE)
    else:
        amount = rng.uniform(*AMOUNT_SMALL_RANGE)
    return round(amount, 2)


# ── Customer generation ────────────────────────────────────────────────────────

def generate_customers(rng: random.Random) -> list[dict]:
    """
    Create N_CUSTOMERS synthetic customers with varying payment histories.

    Three archetypes (roughly):
      - "Loyal"  (~30%): high total payments, high success rate
      - "Average" (~50%): moderate history, mixed success
      - "New/Risky" (~20%): few or no prior payments
    """
    customers = []
    for i in range(N_CUSTOMERS):
        cid = f"cust_{i+1:04d}"
        archetype = rng.choices(
            ["loyal", "average", "new"],
            weights=[0.30, 0.50, 0.20],
        )[0]

        if archetype == "loyal":
            total     = rng.randint(20, 100)
            success_r = rng.uniform(0.80, 0.97)
        elif archetype == "average":
            total     = rng.randint(5, 30)
            success_r = rng.uniform(0.50, 0.80)
        else:   # new / risky
            total     = rng.randint(0, 5)
            success_r = rng.uniform(0.20, 0.55)

        successful = round(total * success_r)
        failed     = total - successful
        ltv        = round(successful * rng.uniform(800.0, 3500.0), 2)
        pref_chan  = rng.choice(["SMS", "EMAIL"])
        email      = f"user_{cid}@example.com"
        phone      = f"+9198{rng.randint(10000000, 99999999)}"

        # Validate against our Pydantic model before storing
        cust = Customer(
            customer_id=cid,
            total_payments=total,
            successful_payments=successful,
            failed_payments=failed,
            lifetime_value=ltv,
            preferred_channel=pref_chan,
            email=email,
            phone=phone,
        )
        customers.append(cust.model_dump())

    return customers


# ── Ground-truth oracle ────────────────────────────────────────────────────────
# This function is intentionally DIFFERENT from the scoring in diagnosis.py.
# Base rates, noise levels, and customer-history weighting all differ so that
# Phase 7 evaluation metrics are honest and not self-fulfilling.

_ORACLE_BASE_RATES: dict[FailureReason, float] = {
    FailureReason.BANK_SERVER_DOWN:   0.80,   # vs ~0.85 in diagnosis heuristic
    FailureReason.INSUFFICIENT_FUNDS: 0.30,   # vs ~0.40
    FailureReason.NETWORK_TIMEOUT:    0.75,   # vs ~0.80
    FailureReason.CARD_EXPIRED:       0.25,   # vs ~0.20
    FailureReason.INVALID_OTP:        0.48,   # vs ~0.50
}

def _ground_truth_oracle(
    rng: random.Random,
    failure_reason: FailureReason,
    customer: dict,
    previous_attempts: int,
    amount: float,
) -> bool:
    """
    Decide whether this payment WOULD genuinely recover if contacted correctly.
    Uses a different random seed path than diagnosis.py to avoid circularity.

    Returns True (recoverable) or False (not recoverable).
    """
    base = _ORACLE_BASE_RATES[failure_reason]

    # Customer loyalty adjustment (different formula than diagnosis.py)
    total = customer["total_payments"]
    if total > 0:
        success_rate = customer["successful_payments"] / total
        # Slightly nonlinear loyalty bonus
        loyalty_adj = (success_rate - 0.5) * 0.25
    else:
        loyalty_adj = -0.10   # new customer → slight penalty

    # Retry penalty — more attempts → less likely (customer getting annoyed)
    retry_penalty = previous_attempts * 0.12

    # Large-amount penalty — customers are less likely to retry large payments
    amount_penalty = 0.05 if amount > 10_000 else 0.0

    p = base + loyalty_adj - retry_penalty - amount_penalty

    # 10% chance of a "surprise" exception in either direction
    # (real-world noise: a loyal customer who genuinely can't pay, or a
    #  new customer who surprisingly comes back)
    surprise_roll = rng.random()
    if surprise_roll < 0.05:
        p += 0.30    # pleasant surprise
    elif surprise_roll < 0.10:
        p -= 0.30    # unpleasant surprise

    p = max(0.01, min(0.99, p))   # clamp to avoid 0/1 degenerate cases
    return rng.random() < p


# ── Payment generation ─────────────────────────────────────────────────────────

def generate_payments(
    rng: random.Random,
    customers: list[dict],
) -> tuple[list[dict], list[dict]]:
    """
    Generate N_PAYMENTS failed payments + corresponding ground_truth rows.
    Returns (payments_list, ground_truth_list).
    """
    payments     : list[dict] = []
    ground_truths: list[dict] = []
    invalid_count = 0

    for i in range(N_PAYMENTS):
        pid      = f"pay_{uuid.uuid4().hex[:10]}"
        customer = rng.choice(customers)
        amount   = _random_amount(rng)
        reason   = _weighted_choice(rng, FAILURE_WEIGHTS)
        method   = _weighted_choice(rng, METHOD_WEIGHTS)
        ts       = _random_timestamp(rng)
        attempts = rng.choices(
            [0, 1, 2, 3],
            weights=[0.50, 0.25, 0.15, 0.10],
        )[0]

        try:
            pmt = Payment(
                payment_id=pid,
                customer_id=customer["customer_id"],
                amount=amount,
                status=PaymentStatus.FAILED,
                failure_reason=reason,
                payment_method=method,
                timestamp=ts,
                previous_attempts=attempts,
            )
            payments.append(pmt.model_dump())

            # Generate hidden label — use a FRESH random call sequence so the
            # oracle's randomness is independent from the payment's fields
            outcome = _ground_truth_oracle(
                rng=rng,
                failure_reason=reason,
                customer=customer,
                previous_attempts=attempts,
                amount=amount,
            )
            ground_truths.append({
                "payment_id":              pid,
                "actual_recovery_outcome": int(outcome),   # SQLite stores as int
            })

        except Exception as exc:
            invalid_count += 1
            logger.warning(
                "data.invalid_record_skipped",
                extra={"index": i, "error": str(exc)},
            )

    logger.info(
        "data.payments_generated",
        extra={
            "total":   len(payments),
            "invalid": invalid_count,
        },
    )
    return payments, ground_truths


# ── DB insertion ───────────────────────────────────────────────────────────────

def _insert_customers(customers: list[dict]) -> None:
    with get_connection() as conn:
        conn.executemany(
            """
            INSERT OR REPLACE INTO customers
                (customer_id, total_payments, successful_payments, failed_payments,
                 lifetime_value, preferred_channel, email, phone)
            VALUES (:customer_id, :total_payments, :successful_payments, :failed_payments,
                    :lifetime_value, :preferred_channel, :email, :phone)
            """,
            customers,
        )


def _insert_payments(payments: list[dict]) -> None:
    rows = [
        {
            "payment_id":       p["payment_id"],
            "customer_id":      p["customer_id"],
            "amount":           p["amount"],
            "status":           p["status"].value if hasattr(p["status"], "value") else p["status"],
            "failure_reason":   p["failure_reason"].value if hasattr(p["failure_reason"], "value") else p["failure_reason"],
            "payment_method":   p["payment_method"].value if hasattr(p["payment_method"], "value") else p["payment_method"],
            "timestamp":        p["timestamp"].isoformat() if hasattr(p["timestamp"], "isoformat") else p["timestamp"],
            "previous_attempts": p["previous_attempts"],
        }
        for p in payments
    ]
    with get_connection() as conn:
        conn.executemany(
            """
            INSERT OR REPLACE INTO payments
                (payment_id, customer_id, amount, status, failure_reason,
                 payment_method, timestamp, previous_attempts)
            VALUES (:payment_id, :customer_id, :amount, :status, :failure_reason,
                    :payment_method, :timestamp, :previous_attempts)
            """,
            rows,
        )


def _insert_ground_truth(ground_truths: list[dict]) -> None:
    with get_connection() as conn:
        conn.executemany(
            """
            INSERT OR REPLACE INTO ground_truth (payment_id, actual_recovery_outcome)
            VALUES (:payment_id, :actual_recovery_outcome)
            """,
            ground_truths,
        )


# ── Reporting ──────────────────────────────────────────────────────────────────

def _print_summary(payments: list[dict], ground_truths: list[dict]) -> None:
    """
    Print a human-facing summary.
    Note: we intentionally DO NOT show actual_recovery_outcome next to each
    sample row — proving that the separation between prediction inputs and
    hidden labels is real.
    """
    # Count by failure reason
    reason_counts: dict[str, int] = {}
    for p in payments:
        r = p["failure_reason"]
        key = r.value if hasattr(r, "value") else str(r)
        reason_counts[key] = reason_counts.get(key, 0) + 1

    total_recoverable = sum(gt["actual_recovery_outcome"] for gt in ground_truths)

    print("\n" + "═" * 60)
    print("  RecoverAI — Phase 1 Data Generation Complete")
    print("═" * 60)
    print(f"  Customers generated  : {N_CUSTOMERS}")
    print(f"  Payments generated   : {len(payments)}")
    print(f"  Ground truth rows    : {len(ground_truths)}")
    print(f"\n  Breakdown by failure reason:")
    for reason, count in sorted(reason_counts.items()):
        pct = count / len(payments) * 100
        print(f"    {reason:<25} {count:>4}  ({pct:.1f}%)")

    print(f"\n  [HIDDEN] Recoverable payments (ground truth): {total_recoverable}")
    print(f"  [HIDDEN] Recovery base rate: {total_recoverable / len(payments):.1%}")
    print("  ↑ These numbers are shown here for your reference only.")
    print("    The pipeline code never reads ground_truth at decision time.")

    print("\n  Sample payments (5 rows — WITHOUT hidden outcome):")
    print(f"  {'payment_id':<18} {'customer_id':<12} {'amount':>8}  {'failure_reason':<25} {'prev_att':>8}")
    print("  " + "-" * 80)

    import random as _random
    sample_rng = _random.Random(999)   # Separate seed for sampling
    sample = sample_rng.sample(payments, 5)
    for p in sample:
        reason = p["failure_reason"].value if hasattr(p["failure_reason"], "value") else p["failure_reason"]
        print(
            f"  {p['payment_id']:<18} {p['customer_id']:<12} "
            f"₹{p['amount']:>8,.2f}  {reason:<25} {p['previous_attempts']:>8}"
        )

    print("═" * 60 + "\n")


# ── Entry point ────────────────────────────────────────────────────────────────

def main() -> None:
    setup_logging()
    logger.info("data.generation.start", extra={"seed": RANDOM_SEED, "n_payments": N_PAYMENTS})

    rng = random.Random(RANDOM_SEED)

    # 1. Drop existing tables and recreate (fresh run)
    drop_all_tables()
    init_db()

    # 2. Generate customers
    customers = generate_customers(rng)

    # 3. Generate payments + hidden ground truth
    payments, ground_truths = generate_payments(rng, customers)

    # 4. Insert into DB
    _insert_customers(customers)
    _insert_payments(payments)
    _insert_ground_truth(ground_truths)

    logger.info(
        "data.generation.complete",
        extra={
            "customers": len(customers),
            "payments":  len(payments),
            "db":        os.getenv("DATABASE_URL", "recoverai.db"),
        },
    )

    # 5. Human-facing summary (print OK here — this IS the final human output)
    _print_summary(payments, ground_truths)


if __name__ == "__main__":
    main()
