"""
models/schemas.py — Pydantic data models for RecoverAI 2.0.

Autonomous Revenue-Recovery Agent data structures supporting:
  - Failure & Abandonment Diagnosis
  - Customer-aware context (LTV, loyalty, channel preference)
  - Multi-step structured Recovery Plans
  - Revenue prioritization (Expected Value, Priority Tiers)
  - Deterministic Guardrails & Bounded Escalations
  - Audit trails and Ground-Truth verification
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, field_validator


# ── Enumerations ──────────────────────────────────────────────────────────────

class EventType(str, Enum):
    PAYMENT_FAILED     = "PAYMENT_FAILED"
    CHECKOUT_ABANDONED = "CHECKOUT_ABANDONED"


class FailureReason(str, Enum):
    BANK_SERVER_DOWN        = "BANK_SERVER_DOWN"
    INSUFFICIENT_FUNDS      = "INSUFFICIENT_FUNDS"
    NETWORK_TIMEOUT         = "NETWORK_TIMEOUT"
    CARD_EXPIRED            = "CARD_EXPIRED"
    INVALID_OTP             = "INVALID_OTP"
    TEMPORARY_GATEWAY_ERROR = "TEMPORARY_GATEWAY_ERROR"
    CHECKOUT_ABANDONED      = "CHECKOUT_ABANDONED"
    FRAUD_SUSPECTED         = "FRAUD_SUSPECTED"


class PaymentMethod(str, Enum):
    UPI           = "UPI"
    CREDIT_CARD   = "CREDIT_CARD"
    DEBIT_CARD    = "DEBIT_CARD"
    NET_BANKING   = "NET_BANKING"
    WALLET        = "WALLET"
    CHECKOUT_CART = "CHECKOUT_CART"


class PaymentStatus(str, Enum):
    FAILED    = "FAILED"
    PENDING   = "PENDING"
    SUCCESS   = "SUCCESS"
    ESCALATED = "ESCALATED"
    RECOVERED = "RECOVERED"   # Payment link was actually paid — confirmed by Razorpay


class RecoveryAction(str, Enum):
    """Actions the AI agent can recommend (and the executor can carry out)."""
    WAIT                     = "WAIT"
    WAIT_AND_RECHECK         = "WAIT_AND_RECHECK"
    RECHECK_STATUS           = "RECHECK_STATUS"
    SEND_PAYMENT_LINK        = "SEND_PAYMENT_LINK"
    ALTERNATE_PAYMENT_METHOD = "ALTERNATE_PAYMENT_METHOD"
    RETRY                    = "RETRY"
    ESCALATE_TO_HUMAN        = "ESCALATE_TO_HUMAN"
    STOP                     = "STOP"


class RecoveryPlaybook(str, Enum):
    """Failure-specific recovery playbooks."""
    TEMPORARY_BANK_FAILURE       = "TEMPORARY_BANK_FAILURE"
    NETWORK_TIMEOUT              = "NETWORK_TIMEOUT"
    INSUFFICIENT_FUNDS           = "INSUFFICIENT_FUNDS"
    CARD_EXPIRED                 = "CARD_EXPIRED"
    INVALID_OTP                  = "INVALID_OTP"
    CHECKOUT_ABANDONED           = "CHECKOUT_ABANDONED"
    HIGH_VALUE_GUARDRAIL_BLOCK   = "HIGH_VALUE_GUARDRAIL_BLOCK"
    UNKNOWN_FAILURE              = "UNKNOWN_FAILURE"


class RecoveryStage(str, Enum):
    """Progressive lifecycle stages of the recovery workflow."""
    WEBHOOK_RECEIVED      = "WEBHOOK_RECEIVED"
    DIAGNOSED             = "DIAGNOSED"
    PLAYBOOK_SELECTED     = "PLAYBOOK_SELECTED"
    RECOVERY_PLAN_CREATED = "RECOVERY_PLAN_CREATED"
    WAIT_SCHEDULED        = "WAIT_SCHEDULED"
    STATUS_RECHECKED      = "STATUS_RECHECKED"
    GUARDRAIL_CHECKED     = "GUARDRAIL_CHECKED"
    ACTION_EXECUTED       = "ACTION_EXECUTED"
    PAYMENT_VERIFIED      = "PAYMENT_VERIFIED"
    STOPPED               = "STOPPED"


class StrategyType(str, Enum):
    """Failure-specific & customer-specific strategy playbooks."""
    INTELLIGENT_RETRY              = "INTELLIGENT_RETRY"
    CHECKOUT_ABANDONMENT_RECOVERY = "CHECKOUT_ABANDONMENT_RECOVERY"
    ALTERNATE_PAYMENT_LINK         = "ALTERNATE_PAYMENT_LINK"
    FUNDS_COOLDOWN_REMINDER        = "FUNDS_COOLDOWN_REMINDER"
    BOUNDED_ESCALATION             = "BOUNDED_ESCALATION"
    STOP_UNRECOVERABLE             = "STOP_UNRECOVERABLE"


class ChannelPreference(str, Enum):
    """Customer communication channels."""
    SMS      = "SMS"
    EMAIL    = "EMAIL"
    WHATSAPP = "WHATSAPP"


class PriorityTier(str, Enum):
    """Revenue opportunity priority levels."""
    HIGH   = "HIGH"
    MEDIUM = "MEDIUM"
    LOW    = "LOW"


class GuardrailOutcome(str, Enum):
    APPROVED = "APPROVED"
    BLOCKED  = "BLOCKED"


class AttemptStatus(str, Enum):
    SUCCESS = "SUCCESS"
    FAILED  = "FAILED"
    PENDING = "PENDING"


# ── Structured Multi-Step Recovery Plan ───────────────────────────────────────

class RecoveryStep(BaseModel):
    """A discrete, executable step within a multi-step Recovery Plan."""
    step_number:      int
    action:           RecoveryAction
    duration_minutes: Optional[int] = None
    delay_seconds:    Optional[int] = 0
    channel:          Optional[ChannelPreference] = None
    description:      str
    is_completed:     bool = False


class RecoveryPlan(BaseModel):
    """
    Structured multi-step recovery roadmap generated by RecoverAI.
    Shows the merchant exactly how the agent plans to recover revenue autonomously.
    """
    plan_id:                 str
    payment_id:              str
    strategy:                StrategyType
    playbook:                Optional[str] = "TEMPORARY_BANK_FAILURE"
    stage:                   Optional[str] = "WAIT_SCHEDULED"
    delay_seconds:           Optional[int] = 0
    scheduled_at:            Optional[datetime] = None
    steps:                   List[RecoveryStep] = Field(default_factory=list)
    priority:                PriorityTier = PriorityTier.MEDIUM
    expected_recovery_value: float = 0.0
    created_at:              datetime = Field(default_factory=datetime.utcnow)


# ── Core Data Models ──────────────────────────────────────────────────────────

class Customer(BaseModel):
    """Aggregated history & preferences for one customer."""
    customer_id:          str
    total_payments:       int   = Field(ge=0)
    successful_payments:  int   = Field(ge=0)
    failed_payments:      int   = Field(ge=0)
    lifetime_value:       float = Field(default=0.0, ge=0.0)
    preferred_channel:    ChannelPreference = ChannelPreference.SMS
    email:                Optional[str] = None
    phone:                Optional[str] = None

    @field_validator("failed_payments")
    @classmethod
    def failed_lte_total(cls, v: int, info) -> int:
        total = info.data.get("total_payments", 0)
        if v > total:
            raise ValueError(
                f"failed_payments ({v}) cannot exceed total_payments ({total})"
            )
        return v

    @property
    def success_rate(self) -> float:
        """Fraction of payments that succeeded (0.0 – 1.0)."""
        if self.total_payments == 0:
            return 0.0
        return self.successful_payments / self.total_payments


class Payment(BaseModel):
    """A single failed payment or checkout event entering the recovery pipeline."""
    payment_id:         str
    customer_id:        str
    amount:             float = Field(gt=0, description="Amount in INR (₹)")
    status:             PaymentStatus
    failure_reason:     FailureReason
    payment_method:     PaymentMethod
    timestamp:          datetime
    previous_attempts:  int = Field(ge=0, default=0)
    event_type:         EventType = EventType.PAYMENT_FAILED

    @field_validator("status")
    @classmethod
    def must_be_failed(cls, v: PaymentStatus) -> PaymentStatus:
        if v == PaymentStatus.SUCCESS:
            raise ValueError(
                "A successful payment should not enter the recovery pipeline."
            )
        return v


class CheckoutEvent(BaseModel):
    """Checkout abandonment event."""
    checkout_id:       str
    customer_id:       str
    cart_value:        float = Field(gt=0)
    drop_off_stage:    str   # e.g., "PAYMENT_METHOD_SELECTION", "OTP_SCREEN", "REVIEW"
    time_spent_seconds: int  = 60
    timestamp:         datetime = Field(default_factory=datetime.utcnow)
    customer_email:    Optional[str] = None
    customer_phone:    Optional[str] = None


class RecoveryScore(BaseModel):
    """
    Output of Diagnosis & ML Scorer.
    Calculates recoverable probability, expected value, and priority tier.
    """
    payment_id:              str
    is_temporary:            bool   # True if failure is transient (server/network)
    is_recoverable:          bool   # True if recovery action makes sense
    recovery_probability:    float  = Field(ge=0.0, le=1.0)
    expected_recovery_value: float  = Field(default=0.0, ge=0.0)
    priority_tier:           PriorityTier = PriorityTier.MEDIUM
    diagnosis_notes:         str    = ""


class AgentDecision(BaseModel):
    """
    Output of AI Agent layer.
    Recommends initial action, chooses failure-specific strategy,
    selects customer channel, and generates the multi-step Recovery Plan.
    """
    payment_id:          str
    diagnosis:           str                # Short label, e.g. "temporary_service_failure"
    recommended_action:  RecoveryAction
    strategy_type:       StrategyType       = StrategyType.INTELLIGENT_RETRY
    preferred_channel:   ChannelPreference  = ChannelPreference.SMS
    reason:              str                # Human-readable justification
    confidence:          float              = Field(ge=0.0, le=1.0)
    plan:                Optional[RecoveryPlan] = None


class GuardrailResult(BaseModel):
    """
    Output of Deterministic Guardrail Engine.
    Enforces amount bounds, cooldowns, contact limits, and bounded escalations.
    """
    payment_id:       str
    result:           GuardrailOutcome
    reason:           str
    final_action:     RecoveryAction   # What will actually execute
    rule_triggered:   Optional[str] = None


class RecoveryAttempt(BaseModel):
    """One row in the recovery_attempts table."""
    attempt_id:   str
    payment_id:   str
    action:       RecoveryAction
    status:       AttemptStatus
    reason:       str
    timestamp:    datetime
    channel_used: Optional[ChannelPreference] = None


class AuditLogEntry(BaseModel):
    """
    Complete pipeline run record stored in audit_logs.
    """
    event_id:           str
    payment_id:         str
    ml_score:           float             # recovery_probability
    expected_value:     float             = 0.0
    priority_tier:      str               = "MEDIUM"
    ai_diagnosis:       str
    ai_recommendation:  RecoveryAction
    strategy_type:      str               = "INTELLIGENT_RETRY"
    channel_used:       str               = "SMS"
    guardrail_result:   GuardrailOutcome  # APPROVED or BLOCKED
    action_taken:       RecoveryAction    # what was executed
    result:             AttemptStatus     # SUCCESS, FAILED, PENDING
    timestamp:          datetime


class GroundTruth(BaseModel):
    payment_id:                str
    actual_recovery_outcome:   bool


# ── User & Authentication Schemas ─────────────────────────────────────────────

class MerchantProfileResponse(BaseModel):
    merchant_id:   str
    name:          str
    business_name: str
    email:         Optional[str] = None
    phone:         Optional[str] = None
    created_at:    Optional[str] = None
    updated_at:    Optional[str] = None


class UserRegisterRequest(BaseModel):
    email:        str = Field(..., min_length=3, max_length=255)
    password:     str = Field(..., min_length=8, max_length=128)
    full_name:    str = Field(..., min_length=1, max_length=100)
    company_name: str = Field(default="My Store", max_length=100)
    business_name: Optional[str] = None
    role:         str = Field(default="OWNER")


class UserLoginRequest(BaseModel):
    email:    str
    password: str


class ForgotPasswordRequest(BaseModel):
    email: str = Field(..., min_length=3, max_length=255)


class ResetPasswordRequest(BaseModel):
    token: str = Field(..., min_length=32, max_length=256)
    new_password: str = Field(..., min_length=8, max_length=128)


class UserProfileResponse(BaseModel):
    user_id:       str
    merchant_id:   str = "mer_default"
    merchant_name: Optional[str] = "RecoverAI Demo Store"
    business_name: Optional[str] = "RecoverAI Retail"
    email:         str
    full_name:     str
    company_name:  str = "RecoverAI Retail"
    role:          str = "OWNER"
    api_key:       Optional[str] = None
    created_at:    Optional[str] = None
    last_login_at: Optional[str] = None


class AuthMeResponse(BaseModel):
    user:     UserProfileResponse
    merchant: MerchantProfileResponse


class AuthTokenResponse(BaseModel):
    access_token: str
    token_type:   str = "bearer"
    user:         UserProfileResponse


class UpdateProfileRequest(BaseModel):
    full_name:    Optional[str] = None
    company_name: Optional[str] = None
    new_password: Optional[str] = None


class UserProfileSummary(BaseModel):
    user_id:      str
    merchant_id:  str = "mer_default"
    email:        str
    full_name:    str
    company_name: str
    role:         str
    is_current:   bool = False
